metadata:
  description: >-
    config for MU-MIP project with UFS
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: fv3lam
platform:
  CCPA_OBS_DIR: ""
  MRMS_OBS_DIR: ""
  NDAS_OBS_DIR: ""
workflow:
  USE_CRON_TO_RELAUNCH: false
  EXPT_SUBDIR: DYAMOND_3km
  CCPP_PHYS_SUITE: FV3_RAP
  PREDEF_GRID_NAME: MUMIP_IO_3km
  DATE_FIRST_CYCL: '2016081012'
  DATE_LAST_CYCL: '2016081012'
  FCST_LEN_HRS: 36
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: netcdf
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_ICS: /scratch2/BMC/fv3lam/MUMIP/icbc_data/GFSreplay/FV3GFS/netcdf/2016081012
task_get_extrn_lbcs:
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: /scratch2/BMC/fv3lam/MUMIP/icbc_data/GFSreplay/FV3GFS/netcdf/2016081012
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: netcdf
task_run_fcst:
  QUILTING: true
task_plot_allvars:
  COMOUT_REF: ""
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
